env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
    # DOCKER_USER
    - secure: "VMGRfwxa2RQU1wZ/ARrSDRBdbkGTdYuFg9++MV2gRbaPpIv8vfu2FI2FuJzeVCyhjwdOs3XhCRDX0GAkjTu1pJfBL2JzvOeT+nHJRvPSrVCjbap3T9nEkznRksOdYctGV6R3SwTJlt5d/v4c4ZYUk8+DRn3r5assWhTqsBrZVkg6BOFWdbi5okQhDRn1wKxJmVjoe8mwJjSS6OxNljYFmFmymEICU/wfBMOJzkkSidjHvxnwhePM/6IdNMuIEafLbtfpMSAgflA8VzDRR543EATrGGnPEhTB1IDHUdoQs/sbjwFAVjmudTw9qeb5fkEikbatsEMXAv2WSL06Jfw9fL6yuKllGnFVY3zDJvHsXbOZA3jesL87qcND+L5nRcT+lMOr/kFDWIRPjqL/6qDGjGnZVe2sgbEiAbx3Wln349ZhSjgLk08TeGdzD7WjsGEU9sZjYeIWTNz0b95ZIYyKkO9bOpaV8If4c/wT2AR6a9YFMMZb5g3T7ScxlcAp9noEE637o0vOsCyxBQDm3p6VNkKPqKHyey2SVU5lNWpoU1+90B5a2oL633HyBz8NgakhC8r+n0EqgqbTF6d4Y4L0DYkfiDd7B7W1286zZaL6AQKDTiwnUU8qTUXjaAlmRb3x+767vOJa2jmIOVTiEjlce+JYkJ5OJ8Q1MYys+npp0bw="
    # DOCKER_PASS
    - secure: "GAw7OzErMZ1Yxidy1hEUi+y4EkOKqFqYH0vdpwIELlP0D3dZn0/u/on0kWYFViMO2lbHy8J5H8KnQRSyfkjpwUaux2PfNnEEJw+cpBx62y7dJ3O6j2DELzgK1ZUhfhQprh3BrhMZ61iCqRqukEA58dvxxv+7Oup2vTOJg9vGwP9ptNspqwKyqwPT9eyxJZWTzfWZr51+1lqp8n6AY9vEg0xHJm820ar0x17HeHWUSWCYemmdAq6BmTNY4UvxHBKRlbSciaVHl3jmKnpZ3CvjN9QQ/PLQdpgWd5ZEjAzmppMkdVbkC+mXd3QtDh5mTfHVIcpe+YLHi61HLAir1nZnLmj4E//DDooxGUhBeCMHALzGruXtMnZIJBdZeW7sdR2/wCISPkGGxLbXj3KYUaqUSfqNYJJePBG9OT9wxKSnQRhm3ZMxV5BtLbqQsFd/4bMQRuP01nZqmbJU/dUyjPLs2bc4R+oSLcsB+/4L0eSChmxZJ+qtEV+yIXzmGIG9q7CxwKsW8tKDtwHsSoKnoRS2CRyjvNmWGIU00zepuw/Du7v+i+Zn1xHtvFK8osumMhik/0FHPFGAZPCV9uTDaYysgoEvqennU0a3hpXMvAu0XB2qCaj7mzecXuBvZjREhp9K6f5lX7PxnbItnwbNyqJIu9O6Cj8rqEgLJLB7tbL1EW8="
    # Where to push Docker image
    - DOCKER_REPO=comfy/imagepuller
services:
  - docker
before_script:
  # Log in to docker hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  # Get version number for this build
  - VERSION=$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER
script:
  # Build and tag the docker image
  - cd controller
  - docker build -t $DOCKER_REPO:$VERSION .
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then docker tag $DOCKER_REPO:$VERSION $DOCKER_REPO:latest; fi
after_success:
  # Show built images
  - docker images
  # Push to Docker Hub
  - docker push $DOCKER_REPO
