env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
    # DOCKER_USER
    - secure: "akx+59++ZWWuu2z3c9rmxW4xQpesXvtLzY9F9uvyuox0rQKDqsJoL38QijC2aX5ih/K/4gN9XTn5qXRhd5l+sNjxVP39dkJMwUpguVWbEZleDfnQ/HOUtfwgLCt0+nm6nAUQWDnlBwO3SAvX+G35Mt0iW2bq5Thmu9DqLzLIad5Ht0R7wTuXeS/RBY+Po2Y0HNykBR0GD1lPz68Hw9uYqOoidVoMhwkc6qSXSOuZ9tqv4R6MLbFvpRUOWe8yQbB11eLUOHDO90IHR22dF5uqNKtdYNJ6oVsgtoPUIsglxJ6p76dgJAx/sAEU71dd31nCSpSseQdYtjGnCJKdR5hxAzVPzZS9wMdsYJvk4j+W7evQkerrdUjB5wZ6oq+qNC+SG6/UPX8+Ej9DpXN4PB3B340lZZBRqZS3G+tEDqi4fhMvhMHRrxiSJ8LqBuahSrG0h/sx5GFKoOxOyCWjLOZEzc5My3D+EfX74Ih0ZUeFyxhg8ofApYG4hLCOqAah//tFK5EfsgchywxFN2mEn2iKRiQC+zzy8IDO63cOrPcfC6akvh8twMVnbKmsmjtKyhxnJm/rmvXyZjXT+93ETUHeVEHe7RMoKPCzWWyJ625t9t844RIG/TfzhQiE59VIK88e7XJSCQWwBc2vg512ScMetTrDLoo7L5TUFpwbiwYtoZI="
    # DOCKER_PASS
    - secure: "W5UDKmhV3HUhGVtCOl0bU7OW7M1R7qYEK/p4EPPLUJhtUWKC6hviV33fEhQKsqg9Nblixt3A1RWZzLtole10AHf3JPe9LJ3Hkg06Sx7AsD3tmdzybwYdHNkxCzMn7t9AvpAUKiDZVxHvSP2ZPE3o+pi2s9RNoM//fhXktSuxgCP4685TOLMmJaM4zLZTMs9h/03wRkRKFHZssgb+heYY0j/IBCTgU3aO3BF4nyjhiHvpbqUndPOOhd40UuiKwgjI2GySbfb+OMXBCxxqNTrTlG76JY0NOBi8cjCMxC2oJYkk8rFtXEMSXUETNycAaUOPWgkUTA6Jnj9cjysH0p0pTnTq9SZ6yJCgsEZ4qsfnyTe/SrNEPjC64WyPIZwFgucgeXn02jeyTvDLzB7/osJKmG4C8gcJqNDr0KvxesRbmEGuyCaS41tow8+uQRWPbT1sp3PNx1Vy0r/YujcSyXx/c41uohXi0e0bdh95tpeKnUnh0JnJIP77s2V5hDUJmzw/TWxPzdQrnWRRex2c/Ai4e9fE8PdCo8V0fXLLwmU8LxPVouhux8fY9IpuwjfQm8+zDhkHA7k6Qn2xkn+N/9Fwc8z6TQK4xJ79JMM2M0fOi4iizC0Gy21a9rqOviPHgv9OQEvFNp6ZnwyWWVl/K+pCoCJ8/XPR+3mWBKYyAkOOmIE="
    # Where to push Docker image
    - DOCKER_REPO=comfy/imagepuller
services:
  - docker
before_script:
  # Log in to docker hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  # Get version number for this build
  - VERSION=$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER
script:
  # Build and tag the docker image
  - docker build -t $DOCKER_REPO:$VERSION .
  - test "${TRAVIS_BRANCH}" = "master" && docker tag $DOCKER_REPO:$VERSION $DOCKER_REPO:latest
after_success:
  # Show built images
  - docker images
  # Push to Docker Hub
  - docker push $DOCKER_REPO
