env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
    # DOCKER_USER
    - secure: "ADfbcX+mdqTfKSUniquXhsXkxxtthZqN6A/pwRVLGdSPT9OdrrUGyli19PaQ6SkMN5u0JN1tiz00cOPQbDzTrTyFwC7t3fGKHeTonRNaCdLmyJeRN5gxaoBLK41DXsMVbxTNSgGZYf62nPsKElyq99ztyUsz7QEUIXdMCYkbjQlX3eQ7dVqgKjC/iND+ewcT3t8BFgOQK4ak2MV+0S9ELZ7keynqaDqZ/ZZO3L41Q+1IB0Gyo/IjxKWWd3DblFLi/50Ma3UqzZmzmTP8dBDF5TTMIZ/jFbYN0J7oW8DYakfC+A1LBfBD1VaY45LYYkIXJzXdtb8MTGexR6UBc4zJp9K0kbyB7Xgb29Bmp3mg3gmTiQQKDdE/EeKrfbd3mO0Iuy0hK4Byp436l+acO6Prg+MOoJXB/KIQuCi7xBceVg3ETGhJVqmZjZDY4Ycbov70R1PXwJVagXi47ildGX3dyA3Pzat73pTmsn8GIEWGgQdD5qusbN11gvn6eTG30Tfmen0IlqbhSY7yFDc/yh4wkzfsYY0B8zcebcPFd8GzqGi2CgFC+YKiloOtW6GSbZQKOlwAuCmlo+d0kDJs7RVSJA0fPxzpVughYQ7r+3hvL6GSJmXz2I/FrRRtBz0cxSAvtGVMZEW39SI5sr7Sf8JsdhcqR3StlYXrVP/MajxeHAY="
    # DOCKER_PASS
    - secure: "FopOrD3CeWkYq549BtVBQ7pFuOoEFDulyLlGivi6rhNUZ92XGqMGq3GAkztmi4ZmcIYz03SwcNohL9TEfhPyVQcJqyREU5sfrBUePO2IUZj6R2Bh6pnrKlh0EwnqRLav84Aw1bLTPT1YAZ6vrrLpqKs+hpkyFDvJi1B/OmUs20iLZkvgZam8smEAj5/iruy809hbcFgFoJl08PtCLMhy05Ih24dyhccXteWUdnZJZ5Hscvvgdd04NkK4RweaU8zlEXK8iipoqB53/ZkPNXmigLI5OwAS684+RCt09iEYkzfbWwseyYXUXG8ZFUOFm1dJKZgFlJJpG+cXOHRZwh6xsK07tUXICh3MxD16WpJep7WJrZL4BJmwkY6zb+/+iL5Q++UY4SOpBGroOWtQ/TanDuGPO8QMu2LjPvlqBBRsqpDCJIWVbkHFpWgVEdMJaQ9CU4elQ4rnz5QEpjD+Y5Qzomt7EmVJFeMn7P9qWbq3tD+LGckT7trY6X7l1BhelHySqunlBxwFoL/N1C3NK+L7UX0RCV2zuRQstGi1q0UHyYagEiSeW1Q7UdfKftd87JuY2xlycyggl/+ouF6ic43EZtxWLimNadPC8mihK0ig6gFPNSbgKd4f/wCBoAe3zf/4BCiMIbGkrz0lo8X7sFMidNol9aEABb27gO1IM7xRsM8="
    # Where to push Docker image
    - DOCKER_REPO=comfy/imagepuller
services:
  - docker
before_script:
  # Log in to docker hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  # Get version number for this build
  - VERSION=$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER
script:
  # Build and tag the docker image
  - docker build -t $DOCKER_REPO:$VERSION .
  - test "${TRAVIS_BRANCH}" = "master" && docker tag $DOCKER_REPO:$VERSION $DOCKER_REPO:latest
after_success:
  # Show built images
  - docker images
  # Push to Docker Hub
  - docker push $DOCKER_REPO
