apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.developers.comfyapp.com
spec:
  group: developers.comfyapp.com
  version: v1
  scope: Cluster
  names:
    plural: images
    singular: image
    kind: Image
    shortNames:
     - im
